package io.github.stoicswe.eyeandsickle.server.identity;

import io.github.stoicswe.eyeandsickle.protocol.game.Ethecoin;
import io.github.stoicswe.eyeandsickle.protocol.game.Faction;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * One character as this home server knows them — the authoritative record, read from {@code players}.
 *
 * <h2>A character, within an account</h2>
 *
 * A {@code players} row is a <em>character</em>: an independent game identity with its own ethecoin,
 * rig, faction, heat and items ({@code docs/architecture/09-player-state-portability.md} §1). The
 * <em>account</em> is the {@link #did()} — one AT Proto identity — and an account may hold up to
 * {@code EYEANDSICKLE_MAX_CHARACTERS} characters, each in its own {@link #slot()}. This record keeps its
 * name ({@code Player}) rather than being renamed to {@code Character}, because "character" and
 * {@code java.lang.Character} would collide on every import; the vocabulary lives in the field names and
 * the surrounding services instead.
 *
 * <h2>Two identifiers, on purpose</h2>
 *
 * {@link #playerId()} is this server's local key and is what every foreign key in the schema points at —
 * it is also the character's id (a character is a {@code players} row). {@link #did()} is the portable
 * account identity that travels between servers and signs provenance
 * ({@code docs/architecture/02-identity-and-auth.md} §1). They are separate so a future DID rotation is
 * one row update rather than a cascade, and so the handle — display-only and free to change (§5) — never
 * has to be an identity.
 *
 * <h2>The slot / DID pairing</h2>
 *
 * {@link #did()} and {@link #slot()} are null together or set together (mirroring the schema's
 * {@code ck_players_slot_pairing}): a DID-bound, online character has both, a local, DID-less character
 * (09 §1; {@code players.did} nullable since §4) has neither and is exempt from the slot cap entirely.
 * A record that could represent one without the other would let a reader forget which case they are in;
 * the constructor forbids it.
 *
 * <h2>Not the whole character</h2>
 *
 * This is the identity-and-standing core: who they are, which account and slot, their lifecycle status,
 * their side, heat and balance. Rigs, items, deployed miners and the compute ledger are separate tables
 * owned by other systems and are not folded in here.
 *
 * @param playerId server-local primary key (and the character id), generated by the server, never by a
 *     client
 * @param did the portable AT Proto account identity, or {@code null} for a local-only character
 * @param slot the save slot within the account (1..{@link #MAX_SLOT}), or {@code null} for a local-only
 *     character; set exactly when {@code did} is set
 * @param handle current display handle; not an identity, may be {@code null}, may change
 * @param status the character lifecycle state ({@link CharacterStatus}); {@code active} for a playable
 *     character, terminal once migrated or retired (09 §6.1)
 * @param faction the committed side, or {@link Faction#NONE} while uncommitted
 *     ({@code docs/design/01-core-resources.md} §5)
 * @param personalHeat long-horizon Eye attention accrued from this character's own actions (§4.1)
 * @param ethecoinBalance the authoritative spendable balance, materialised alongside the ledger
 * @param createdAt when the character was created (its first sign-in / creation)
 * @param lastSeenAt the most recent time this character was selected, or {@code null}
 * @param rowVersion optimistic-concurrency guard; the value a version-checked update must match
 */
public record Player(
        UUID playerId,
        Did did,
        Integer slot,
        String handle,
        CharacterStatus status,
        Faction faction,
        Heat personalHeat,
        Ethecoin ethecoinBalance,
        Instant createdAt,
        Instant lastSeenAt,
        long rowVersion) {

    /**
     * The lowest slot number a DID-bound character may occupy. Mirrors the lower half of
     * {@code ck_players_slot_bound} in {@code db/migration/core/V3__character_slots.sql}.
     */
    public static final int MIN_SLOT = 1;

    /**
     * The highest slot number a DID-bound character may occupy — the generous structural bound, not the
     * product cap. Mirrors {@code ck_players_slot_bound} in {@code V3__character_slots.sql}. The real,
     * soft cap on how many characters an account may hold is {@code CharacterProperties.maxCharacters}
     * (default 3), enforced in the service; this is only the range a single slot number may take.
     */
    public static final int MAX_SLOT = 16;

    public Player {
        Objects.requireNonNull(playerId, "playerId");
        Objects.requireNonNull(status, "status");
        Objects.requireNonNull(faction, "faction");
        Objects.requireNonNull(personalHeat, "personalHeat");
        Objects.requireNonNull(ethecoinBalance, "ethecoinBalance");
        Objects.requireNonNull(createdAt, "createdAt");
        // did and slot are null together or set together — the schema's ck_players_slot_pairing, in the
        // one place a value is constructed. A DID-bound character has a slot; a local one has neither.
        if ((did == null) != (slot == null)) {
            throw new IllegalArgumentException("did and slot must be null together (local character) or set "
                    + "together (DID-bound character); was did=" + did + ", slot=" + slot);
        }
        if (slot != null && (slot < MIN_SLOT || slot > MAX_SLOT)) {
            throw new IllegalArgumentException(
                    "slot must be within " + MIN_SLOT + ".." + MAX_SLOT + " for a DID-bound character, was " + slot);
        }
        if (rowVersion < 0) {
            throw new IllegalArgumentException("rowVersion is never negative, was " + rowVersion);
        }
    }

    /**
     * @return whether this is a local, DID-less character — exempt from the slot cap, the character
     *     directory and federation (09 §1)
     */
    public boolean isLocal() {
        return did == null;
    }
}
