package io.github.stoicswe.eyeandsickle.server.items;

import io.github.stoicswe.eyeandsickle.protocol.game.StorageTier;
import io.github.stoicswe.eyeandsickle.protocol.provenance.ProvenanceEnvelope;
import io.github.stoicswe.eyeandsickle.protocol.provenance.ProvenanceEventType;
import io.github.stoicswe.eyeandsickle.protocol.provenance.ProvenanceJson;
import io.github.stoicswe.eyeandsickle.protocol.provenance.ProvenancePayload;
import io.github.stoicswe.eyeandsickle.protocol.provenance.SignatureBlock;
import java.security.SecureRandom;
import java.time.Clock;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Base64;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Issues this server's own provenance records: minting an item, granting one to a player, and recording
 * a trade.
 *
 * <p>These are the three single-issuer events this server signs with its own key ({@code
 * docs/architecture/04-item-provenance.md} §2). Each one produces a signed record, links it to the tip
 * of the item's chain, and writes it alongside the item state it changes <strong>in one
 * transaction</strong> — the record and the holder change are meaningless apart, and the append-only
 * provenance table means a half-written transfer cannot be tidied up afterwards.
 *
 * <h2>Timestamps and nonces are generated here</h2>
 *
 * The payload's {@code timestamp} and {@code nonce} are inputs to the signed bytes ({@code 04} §2), and
 * this is where they come from — a {@link Clock} and a {@link SecureRandom}, both injected, so the
 * whole thing is deterministic under test. The nonce is 128 bits, the size §2 specifies for defeating
 * replay of an old record as a new event.
 *
 * <h2>What it does not do</h2>
 *
 * It does not decide <em>whether</em> a player may receive an item, what an item is worth, or who won a
 * trade — those are other systems' rules, and a gate or price check that belonged here would be a
 * balance value smuggled into the provenance layer. This service is handed a decision already made and
 * turns it into a signed, chained, persisted fact.
 */
public class ItemProvenanceService {

    private static final DateTimeFormatter ISO = DateTimeFormatter.ISO_INSTANT;
    private static final int NONCE_BYTES = 16;

    private final Clock clock;
    private final SecureRandom random;
    private final ProvenanceSigner signer;
    private final ItemStore items;
    private final ProvenanceStore provenance;

    /**
     * @param clock source of record timestamps; UTC in production
     * @param random source of record nonces
     * @param signer this server's signing identity
     * @param items item persistence
     * @param provenance provenance-chain persistence
     */
    public ItemProvenanceService(
            Clock clock, SecureRandom random, ProvenanceSigner signer, ItemStore items, ProvenanceStore provenance) {
        this.clock = Objects.requireNonNull(clock, "clock");
        this.random = Objects.requireNonNull(random, "random");
        this.signer = Objects.requireNonNull(signer, "signer");
        this.items = Objects.requireNonNull(items, "items");
        this.provenance = Objects.requireNonNull(provenance, "provenance");
    }

    /**
     * Mints a new item: creates it and writes its genesis {@code initial_mint} record.
     *
     * @param itemId the item's identity, generated by the caller (never by the client)
     * @param itemType e.g. {@code hacking_tool_tier2}
     * @param itemAttrs authoritative stats; the record <em>is</em> the item definition, not a receipt
     * @param holderDid the DID the item is minted to
     * @param storageTier where the freshly minted item is placed
     * @return the stored genesis record
     * @throws IllegalStateException if signing is not configured, or an item with this id already exists
     */
    @Transactional
    public StoredProvenanceRecord mint(
            UUID itemId, String itemType, Map<String, Object> itemAttrs, String holderDid, StorageTier storageTier) {
        Objects.requireNonNull(itemId, "itemId");
        Objects.requireNonNull(itemType, "itemType");
        Objects.requireNonNull(holderDid, "holderDid");
        Objects.requireNonNull(storageTier, "storageTier");
        if (items.exists(itemId)) {
            throw new IllegalStateException(
                    "Item " + itemId + " already exists; an item is minted exactly once (a second initial_mint "
                            + "would be a forked genesis)");
        }

        Instant now = clock.instant();
        ProvenancePayload payload = new ProvenancePayload(
                ProvenancePayload.CURRENT_RECORD_VERSION,
                itemId,
                itemType,
                itemAttrs == null ? Map.of() : itemAttrs,
                ProvenanceEventType.INITIAL_MINT,
                holderDid,
                signer.issuerDid(),
                null,
                0,
                ISO.format(now),
                nonce());
        StoredProvenanceRecord record = signAndBuild(payload, now);

        items.insert(new Item(itemId, itemType, payload.itemAttrs(), holderDid, storageTier, null, now, 0L));
        provenance.append(record);
        return record;
    }

    /**
     * Records this server granting an item it holds to one of its players — a {@code server_grant}.
     *
     * @param itemId the item to grant
     * @param newHolderDid the recipient's DID
     * @return the stored record
     * @throws IllegalStateException if signing is not configured, or the item or its chain is missing
     */
    @Transactional
    public StoredProvenanceRecord serverGrant(UUID itemId, String newHolderDid) {
        return append(itemId, newHolderDid, ProvenanceEventType.SERVER_GRANT);
    }

    /**
     * Records an item changing hands as a trade — a {@code trade}.
     *
     * @param itemId the item traded
     * @param newHolderDid the new owner's DID
     * @return the stored record
     * @throws IllegalStateException if signing is not configured, or the item or its chain is missing
     */
    @Transactional
    public StoredProvenanceRecord trade(UUID itemId, String newHolderDid) {
        return append(itemId, newHolderDid, ProvenanceEventType.TRADE);
    }

    private StoredProvenanceRecord append(UUID itemId, String newHolderDid, ProvenanceEventType eventType) {
        Objects.requireNonNull(itemId, "itemId");
        Objects.requireNonNull(newHolderDid, "newHolderDid");

        Item item = items.find(itemId)
                .orElseThrow(() ->
                        new IllegalStateException("No item " + itemId + " to " + ProvenanceJson.wireName(eventType)));
        StoredProvenanceRecord tip = provenance
                .findTip(itemId)
                .orElseThrow(() -> new IllegalStateException(
                        "Item " + itemId + " has no provenance chain; it cannot be extended before it is minted"));

        Instant now = clock.instant();
        ProvenancePayload payload = new ProvenancePayload(
                ProvenancePayload.CURRENT_RECORD_VERSION,
                itemId,
                // The record restates the item definition (04 §2); its stats carry forward unchanged
                // through a change of hands.
                item.itemType(),
                item.itemAttrs(),
                eventType,
                newHolderDid,
                signer.issuerDid(),
                tip.recordHash(),
                tip.chainDepth() + 1,
                monotonicTimestamp(now, tip.payloadTimestamp()),
                nonce());
        StoredProvenanceRecord record = signAndBuild(payload, now);

        // Item state and the record that authorizes the change, one transaction. Version-checked so two
        // concurrent transfers of the same item cannot both win.
        items.updateHolder(itemId, newHolderDid, item.rowVersion());
        provenance.append(record);
        return record;
    }

    private StoredProvenanceRecord signAndBuild(ProvenancePayload payload, Instant recordedAt) {
        byte[] canonical = ProvenanceJson.canonicalBytes(payload);
        SignatureBlock block = signer.sign(canonical);
        ProvenanceEnvelope envelope = ProvenanceEnvelope.singleIssuer(payload, block);
        String envelopeJson = ProvenanceJson.writeEnvelope(envelope);
        return StoredProvenanceRecord.from(UUID.randomUUID(), envelope, envelopeJson, recordedAt);
    }

    /**
     * The timestamp a new record carries: now, unless the tip is dated later, in which case the tip's.
     *
     * <p>A chain's timestamps must be non-decreasing, or the verifier reports {@code
     * TIMESTAMP_NOT_MONOTONIC}. Within a single server's own appends a monotonic clock guarantees that,
     * but a tip can be a foreign record accepted with a small clock skew and dated slightly ahead of
     * this server's now. Clamping up to it keeps this server from signing a record that would fail its
     * own verifier — at the cost of a timestamp marginally later than the true instant, which is the
     * lesser evil.
     */
    private String monotonicTimestamp(Instant now, String tipTimestamp) {
        try {
            Instant tip = Instant.parse(tipTimestamp);
            return ISO.format(tip.isAfter(now) ? tip : now);
        } catch (DateTimeParseException e) {
            // A tip we cannot parse is not something to reason about; use our own clock.
            return ISO.format(now);
        }
    }

    private String nonce() {
        byte[] bytes = new byte[NONCE_BYTES];
        random.nextBytes(bytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }
}
