package io.github.stoicswe.eyeandsickle.solo.rules;

import io.github.stoicswe.eyeandsickle.protocol.game.ComputeConsumer;
import io.github.stoicswe.eyeandsickle.solo.state.AllocationState;
import io.github.stoicswe.eyeandsickle.solo.state.SoloSave;
import io.github.stoicswe.eyeandsickle.solo.state.TaskState;
import java.time.Instant;

/**
 * How much racket the rig is making right now — the number the status strip's meter draws.
 *
 * <h2>Noise is not load, and this class exists because that kept being forgotten</h2>
 *
 * {@code docs/design/08-stealth-and-noise.md} §1: "noise is generated by <b>acting</b>". Three
 * invariants say which acts do not count, and each of them collapses a system if it is broken:
 *
 * <ul>
 *   <li><b>I4</b> — self-mining is immune to detection and generates zero heat. It is the income
 *       floor; a floor that made you loud would not be one, and the whole quiet-play strategy the
 *       economy is built to reward would stop existing.
 *   <li><b>I9</b> — defending your own rig never generates heat. Being wanted must come from
 *       aggression, never from self-defence.
 *   <li>{@code docs/design/04-mining.md} §3.1 — auditing your own rig is free and silent, which is
 *       what makes the discrepancy hunt a thing a player can afford to do often.
 * </ul>
 *
 * So a rig at 100% load on self-mining, defences and local scans reads <b>zero</b> here. That is the
 * headline result and it is correct rather than a bug.
 *
 * <h2>⚠ This lived in the client until 2026-07-27, and that was the wrong house</h2>
 *
 * {@code client/view/RigStatus} computed it, which meant three invariants were being enforced by a
 * view class — the one place {@code docs/design/00-vision-and-pillars.md} §4 says a rule may never
 * live, and the one place a home server's answer could not reach. It moved here so that the rule has
 * one implementation for both session modes and so the client is once again only drawing what it is
 * told.
 *
 * <h2>Two contributions, and only one of them is an allocation</h2>
 *
 * <ol>
 *   <li><b>Held cycles on outward consumers.</b> {@code CONTROL_CHANNEL}, {@code RELAY_HOP} and
 *       {@code BOT_FRAME} are work that reaches other machines. {@code DEPLOYED_MINER} is
 *       deliberately excluded even though it crosses a network: by <b>I6</b> a deployed miner is
 *       charged to the <em>host's</em> rig, so seeing one in your own budget means somebody else's
 *       miner is running on you — that is their noise, and counting it would make being a victim look
 *       like being an aggressor.
 *   <li><b>A running task's stated loudness</b>, {@link TaskState#noiseCycles}. A sweep occupies
 *       almost none of the rig and is one of the loudest things a player can do, so a task declares
 *       its own noise rather than having it derived from its cycles — see
 *       {@code Balance.NET_SWEEP_BASE_NOISE} for why the two were split, and {@code TaskState} for
 *       why the declaration lives on the task instead of in a switch here.
 * </ol>
 *
 * <h2>Loud while it runs, silent the moment it stops</h2>
 *
 * Both contributions are strictly present-tense. A recovering allocation is excluded, and a task is
 * counted only while {@code now} is inside its window — so the meter falls back to whatever the rig
 * was doing the instant the sweep settles. Noise is a <b>rate</b>. What a loud act leaves behind is
 * <em>heat</em>, which is a different field, persisted, and charged by different rules; conflating
 * the two would give the player a number that never came down and no way to read the difference
 * between "I am being loud" and "I have been loud".
 */
public final class NoiseRules {

    private NoiseRules() {}

    /**
     * Noise as a fraction of the rig's capacity, 0–1.
     *
     * @param now the session clock. ⚠ Never {@code Instant.now()} — a running sweep's window is
     *     measured against this, and a rule that reached for the wall clock behind its caller's back
     *     would report a test clock's sweeps as long over and a paused game's as still shouting
     */
    public static double level(SoloSave save, Instant now) {
        if (save == null || save.rig == null || save.rig.totalCycles <= 0) {
            return 0.0d;
        }
        return Math.min(1.0d, outwardCycles(save, now) / (double) save.rig.totalCycles);
    }

    /**
     * The raw figure behind {@link #level}, in cycles.
     *
     * <p>Published separately because the readout says both — a fraction fills the meter and the
     * cycle count is what a player reasons with when deciding whether they can afford to be seen.
     */
    public static long outwardCycles(SoloSave save, Instant now) {
        if (save == null) {
            return 0L;
        }
        long sum = 0L;
        if (save.rig != null && save.rig.allocations != null) {
            for (AllocationState allocation : save.rig.allocations) {
                if (!"ACTIVE".equals(allocation.state)) {
                    // Recovering cycles are cycles the player has already stopped spending on
                    // somebody else's machine. They are unavailable, which is a load fact, not a
                    // loudness one.
                    continue;
                }
                if (reachesOutward(allocation.consumer)) {
                    sum += allocation.cycles;
                }
            }
        }
        sum += taskNoise(save, now);
        return sum;
    }

    /**
     * The declared loudness of every task still running at {@code now}.
     *
     * <p>Summed rather than maxed: two sweeps at once is two lots of packets on two sets of machines,
     * and a player who starts a second one before the first has settled has genuinely doubled what
     * they are radiating. {@link #level} clamps the total, so this cannot read past a full meter.
     *
     * <p>⚠ A task that has passed its end but has not been settled yet contributes nothing. Settling
     * happens on a tick and the meter is read on a repaint, so between the two there is a window of
     * up to one frame in which a finished sweep is still on {@code save.tasks} — counting it would
     * make the meter hold a moment past the countdown reaching zero, which is precisely the
     * "contributes after it has finished" behaviour this model exists to rule out.
     */
    private static long taskNoise(SoloSave save, Instant now) {
        if (save.tasks == null || now == null) {
            return 0L;
        }
        long sum = 0L;
        for (TaskState task : save.tasks) {
            if (task.noiseCycles > 0 && !task.isFinishedAt(now)) {
                sum += task.noiseCycles;
            }
        }
        return sum;
    }

    /**
     * Whether a consumer's held cycles are work that reaches other machines.
     *
     * <p>Exhaustive over {@link ComputeConsumer} on purpose — no {@code default}. A new consumer must
     * be classified by whoever adds it, at compile time, rather than defaulting to silent and being
     * discovered by a player who was loud and had no way to tell.
     */
    private static boolean reachesOutward(String consumer) {
        ComputeConsumer kind;
        try {
            kind = ComputeConsumer.valueOf(consumer);
        } catch (IllegalArgumentException | NullPointerException unknown) {
            // A hand-edited save. Silent rather than loud: inventing noise from a value nothing in
            // this build wrote would be unaccountable on a meter whose job is to be accounted for.
            return false;
        }
        return switch (kind) {
            case CONTROL_CHANNEL, RELAY_HOP, BOT_FRAME -> true;
            case SELF_MINING, DEFENSIVE_ARRAY, ACTIVE_TOOL, DEPLOYED_MINER -> false;
        };
    }
}
